version: "3.8"

services:
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: >
      sh -c "chmod -R 777 /var/www/storage /var/www/bootstrap/cache && php-fpm"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-commerce-vue-laravel
      MYSQL_USER: e-commerce-vue-laravel
      MYSQL_PASSWORD: e-commerce-vue-laravel
    ports:
      - "3308:3306"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"   
    volumes:
      - ./laravel:/var/www
      - ./nginx.temp.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
